/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_nzdis_example02_ExampleView */

#ifndef _Included_org_nzdis_example03_ExampleView
#define _Included_org_nzdis_example03_ExampleView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_nzdis_example02_ExampleView
 * Method:    myDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_nzdis_example03_GLESView_myDrawFrame
  (JNIEnv *, jclass);

/*
 * Class:     org_nzdis_example02_ExampleView
 * Method:    mySurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_nzdis_example03_GLESView_mySurfaceChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_nzdis_example02_ExampleView
 * Method:    mySurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_nzdis_example03_GLESView_mySurfaceCreated
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
